/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

val smokeTest by configurations.creating {
    extendsFrom(configurations.testImplementation.get())
}

dependencies {
    implementation("com.h2database:h2:2.1.210")
    implementation("jakarta.persistence:jakarta.persistence-api:2.2.3")
    implementation("com.github.peteroupc:numbers:1.8.0")

    smokeTest("org.apache.httpcomponents:httpclient:4.5.5")

    runtimeOnly(group = "org.hibernate", name = "hibernate", version = "3.0.5") {
        isTransitive = true
    }
}

group = "de.tdosca"
version = "1.0"
description = "tdosca-tc09"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
