/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
    jcenter()
}

val smokeTest by configurations.creating {
    extendsFrom(configurations.testImplementation.get())
}

dependencies {
    implementation("com.h2database:h2:2.1.210")
    implementation("jakarta.persistence:jakarta.persistence-api:2.2.3")
    implementation("com.github.peteroupc:numbers:1.8.0")

    testImplementation("junit:junit:4.13.2")
    smokeTest("org.apache.httpcomponents:httpclient:4.5.13")
    runtimeOnly("org.hibernate:hibernate:5.6.7.Final") {
        isTransitive = true
    }

}

group = "de.tdosca"
version = "1.0"
description = "tdosca-tc09"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
