/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.h2database:h2:2.1.210")
    implementation("jakarta.persistence:jakarta.persistence-api:2.2.3")
    implementation("com.github.peteroupc:numbers:1.8.0")
}

group = "de.tdosca"
version = "1.0"
description = "tdosca-tc09"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
